SELECT M.NAME, M.TELEPHONE,M.ADDRESS,P.PRODUCT_NAME "배달상품",O.ORDER_QTY"수량"
FROM   EC_ORDER O INNER JOIN EC_PRODUCT P
				ON(O.Product_Code = P.Product_Code)
		  INNER JOIN EC_MEMBER M
				ON(O.ORDER_ID = M.USERID)
WHERE  O.GUBUN ='결제'
ORDER  BY 1
/