SELECT P.PRODUCT_NAME "주문상품", O.ORDER_QTY "수량" , P.UNIT_PRICE"단가",O.ORDER_ID,
       (P.UNIT_PRICE * O.ORDER_QTY) "주문금액"
FROM   EC_ORDER O,EC_PRODUCT P 
WHERE  P.PRODUCT_CODE= O.PRODUCT_CODE (+)
ORDER  BY 1
/
