 SELECT STUDENT_ID, COURSE_ID,SCORE,SCORE_ASSIGNED
FROM    SG_SCORES
WHERE  COURSE_ID = 'L1031'
 AND    SCORE >= ALL(SELECT SCORE
                     FROM   SG_SCORES
                     WHERE  COURSE_ID = 'L1031')
/
