SELECT STUDENT_ID, NAME,TITLE, C_NUMBER,SCORE, GRADE
FROM   SG_SCORES INNER JOIN COURSE  USING (COURSE_ID)
                 INNER JOIN STUDENT USING (STUDENT_ID)
WHERE  SCORE IS NOT NULL
ORDER  BY 5 DESC, 4 DESC
/
