SELECT DEPT_ID, NAME ||' '|| POSITION "교수명",
       CONNECT_BY_ISLEAF "노드", LEVEL "레벨",
       SYS_CONNECT_BY_PATH(NAME || POSITION, '/') "경로"
FROM   PROFESSOR
WHERE  LEVEL <= 3 AND MGR IS NOT NULL
START  WITH MGR IS NULL
CONNECT BY PRIOR PROFESSOR_ID = MGR
/
