SELECT SG.STUDENT_ID, YEAR, NAME, C.COURSE_ID, TITLE,
       C_NUMBER, SCORE, GRADE
FROM   SG_SCORES SG, STUDENT S, COURSE C
WHERE  SG.STUDENT_ID = S.STUDENT_ID
  AND  SG.COURSE_ID = C.COURSE_ID
  AND  SG.STUDENT_ID = 'C1701'
ORDER  BY 1, 4
/
