SELECT STUDENT_ID, YEAR,NAME,COURSE_ID,TITLE,C_NUMBER,
       SCORE, GRADE
FROM   SG_SCORES INNER JOIN STUDENT USING (STUDENT_ID)
                 INNER JOIN COURSE USING (COURSE_ID)
WHERE  STUDENT_ID = 'C1701'
/
