SELECT SG.STUDENT_ID, YEAR, NAME, SG.COURSE_ID, TITLE,
       C_NUMBER, SCORE, GRADE
FROM   SG_SCORES SG INNER JOIN STUDENT S
                       ON (SG.STUDENT_ID = S.STUDENT_ID)
                    INNER JOIN COURSE C
  			ON (SG.COURSE_ID = C.COURSE_ID)
WHERE  SG.STUDENT_ID = 'C1701'
/
