SELECT CASE GROUPING_ID(DEPT_ID,YEAR)	WHEN 0 THEN DEPT_ID
					WHEN 1 THEN NULL
					WHEN 2 THEN ' 학년계'
					WHEN 3 THEN NULL
	END "학과코드",
	CASE GROUPING_ID(DEPT_ID,YEAR)	WHEN 0 THEN YEAR
					WHEN 1 THEN '  소계'
					WHEN 2 THEN YEAR
					WHEN 3 THEN '전체합계'
	END "학년" , COUNT(*)	"인원수",
	GROUPING_ID(DEPT_ID, YEAR)	"비트벡터"
FROM 	STUDENT
GROUP	BY	CUBE(DEPT_ID,YEAR)
ORDER	BY	Dept_ID
/
